
int bitNor(int, int);
int test_bitNor(int, int);
int thirdBits();
int test_thirdBits();
int copyLSB(int);
int test_copyLSB(int);
int replaceByte(int, int, int);
int test_replaceByte(int, int, int);
int logicalShift(int, int);
int test_logicalShift(int, int);
int greatestBitPos(int);
int test_greatestBitPos(int);
int isTmax(int);
int test_isTmax(int);
int ezThreeFourths(int);
int test_ezThreeFourths(int);
int isAsciiDigit(int);
int test_isAsciiDigit(int);
int isGreater(int, int);
int test_isGreater(int, int);
int isNonZero(int);
int test_isNonZero(int);
int sm2tc(int);
int test_sm2tc(int);
unsigned float_abs(unsigned);
unsigned test_float_abs(unsigned);
unsigned float_half(unsigned);
unsigned test_float_half(unsigned);
unsigned float_i2f(int);
unsigned test_float_i2f(int);
